import { LanguageEnum } from '@freewilltokyo/freewill-be';

export const EXPERIENCE_ORDER_EXPORT_TO_CSV_FIELDS = {
  [LanguageEnum.ENGLISH]: [
    { label: 'Order ID', value: 'orderId' },
    { label: 'Reservation ID', value: 'reservationId' },
    { label: 'User ID', value: 'userId' },
    { label: 'User Name', value: 'userName' },
    { label: 'User Profession', value: 'userProfession' },
    { label: 'User Email', value: 'userEmail' },
    { label: 'User Age', value: 'userAge' },
    { label: 'User Gender', value: 'userGender' },
    { label: 'Experience ID', value: 'experienceNameId' },
    { label: 'Experience Title', value: 'experienceTitle' },
    { label: 'Experience Category Name', value: 'experienceCategory' },
    { label: 'Experience Category Type', value: 'experienceCategoryType' },
    { label: 'Event Start', value: 'evenStart' },
    { label: 'Event End', value: 'eventEnd' },
    { label: 'Ticket Name', value: 'ticketName' },
    { label: 'Ticket Price', value: 'ticketPrice' },
    { label: 'Ticket Status', value: 'ticketStatus' },
    { label: 'Online Ticket', value: 'onlineTicket' },
    { label: 'Offline Ticket', value: 'offlineTicket' },
    { label: 'Ordered at', value: 'orderedAt' },
    { label: 'Commission', value: 'commission' },
    { label: 'Total Amount With Tax', value: 'totalAmountWithTax' },
    { label: 'Payout Amount', value: 'payoutAmount' }
  ],
  [LanguageEnum.JAPANESE]: [
    { label: '注文ID', value: 'orderId' },
    { label: '予約ID', value: 'reservationId' },
    { label: 'ユーザーID', value: 'userId' },
    { label: 'ユーザー名', value: 'userName' },
    { label: 'ユーザーの役職', value: 'userProfession' },
    { label: 'ユーザーメール', value: 'userEmail' },
    { label: 'ユーザー年齢', value: 'userAge' },
    { label: 'ユーザー性別', value: 'userGender' },
    { label: '体験ID', value: 'experienceNameId' },
    { label: '体験タイトル', value: 'experienceTitle' },
    { label: '体験カテゴリー', value: 'experienceCategory' },
    { label: '体験カテゴリータイプ', value: 'experienceCategoryType' },
    { label: 'イベント開始日時', value: 'evenStart' },
    { label: 'イベント終了日時', value: 'eventEnd' },
    { label: 'チケット名', value: 'ticketName' },
    { label: 'チケット金額', value: 'ticketPrice' },
    { label: 'チケットステーテス', value: 'ticketStatus' },
    { label: 'オンライン参加', value: 'onlineTicket' },
    { label: 'オフライン参加', value: 'offlineTicket' },
    { label: '購入日時', value: 'orderedAt' },
    { label: '手数料', value: 'commission' },
    { label: '合計金額(税込)', value: 'totalAmountWithTax' },
    { label: '受取金額', value: 'payoutAmount' }
  ]
};
