version: '3'

services:
  backend:
    container_name: nodejs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN=''
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - app:/home/node
    networks:
      - app-network

  minio:
    image: minio/minio
    volumes:
      - data:/data1
    expose:
      - "9000"
    environment:
      - "MINIO_ACCESS_KEY=${AWS_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${AWS_SECRET_KEY}"
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx-docker-compose
    volumes:
      - ./nginx-docker-compose.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio

networks:
  app-network:
    driver: bridge

volumes:
  app:
  data:
