import { LanguageEnum } from '@freewilltokyo/freewill-be';

export const INSTORE_ORDER_ITEM_PARAMETERS = ['color', 'customParameter'];

export const INSTORE_ORDER_EXPORT_TO_CSV_FIELDS = {
  [LanguageEnum.ENGLISH]: [
    'id',
    { label: 'Order Group', value: 'orderGroupId' },
    { label: 'Order Code', value: 'code' },
    { label: 'Ordered At', value: 'orderedAt' },
    { label: 'Order User Name', value: 'username' },
    { label: 'Order Email', value: 'email' },
    { label: 'Product Name', value: 'orderDetail.productTitle' },
    { label: 'Product Color', value: 'orderDetail.productColor' },
    { label: 'Product Pattern', value: 'orderDetail.productPattern' },
    { label: 'Product Custom Parameter', value: 'orderDetail.productCustomParameter' },
    { label: 'Product Weight', value: 'orderDetail.product.productWeight' },
    { label: 'Product Price With Tax', value: 'orderDetail.productPriceWithTax' },
    { label: 'Product Quantity', value: 'orderDetail.quantity' },
    { label: 'Shipping Fee', value: 'shippingFee' },
    { label: 'Total Amount With Tax', value: 'totalAmount' },
    { label: 'Payout Amount', value: 'payoutAmount' },
    { label: 'Commission', value: 'commission' },
    { label: 'Shipping Name', value: 'shippingName' },
    { label: 'Shipping Postal Code', value: 'shippingPostalCode' },
    { label: 'Shipping Country', value: 'shippingCountry' },
    { label: 'Shipping State', value: 'shippingState' },
    { label: 'Shipping City', value: 'shippingCity' },
    { label: 'Shipping Address Line 1', value: 'shippingAddressLine1' },
    { label: 'Shipping Address Line 2', value: 'shippingAddressLine2' },
    { label: 'Shipping Phone', value: 'shippingPhone' },
    { label: 'Shipping Email', value: 'shippingEmailAddress' }
  ],
  [LanguageEnum.JAPANESE]: [
    'id',
    { label: '注文グループID', value: 'orderGroupId' },
    { label: '注文ID', value: 'code' },
    { label: '注文日付', value: 'orderedAt' },
    { label: 'ユーザネーム', value: 'username' },
    { label: 'E-mail アドレス', value: 'email' },
    { label: '商品名', value: 'orderDetail.productTitle' },
    { label: '商品カラー', value: 'orderDetail.productColor' },
    { label: '商品パターン', value: 'orderDetail.productPattern' },
    { label: 'その他のオプション', value: 'orderDetail.productCustomParameter' },
    { label: '商品重量', value: 'orderDetail.product.productWeight' },
    { label: '商品価格(税込)', value: 'orderDetail.productPriceWithTax' },
    { label: '商品数', value: 'orderDetail.quantity' },
    { label: '送料', value: 'shippingFee' },
    { label: '合計金額(税込)', value: 'totalAmount' },
    { label: '受取金額', value: 'payoutAmount' },
    { label: '手数料', value: 'commission' },
    { label: '配送先_名義', value: 'shippingName' },
    { label: '配送先_郵便番号', value: 'shippingPostalCode' },
    { label: '配送先_国', value: 'shippingCountry' },
    { label: '配送先_都道府県/州', value: 'shippingState' },
    { label: '配送先_市', value: 'shippingCity' },
    { label: '配送先_住所_1', value: 'shippingAddressLine1' },
    { label: '配送先_住所_2', value: 'shippingAddressLine2' },
    { label: '配送先_電話番号', value: 'shippingPhone' },
    { label: '配送先_メールアドレス', value: 'shippingEmailAddress' }
  ]
};
