export enum EmailNotification {
  TELLS_FWSHOP_CUSTOMER_ORDER_COMPLETED = 'TELLS_FWSHOP_CUSTOMER_ORDER_COMPLETED',
  TELLS_FWSHOP_CUSTOMER_ORDER_COMPLETED_GIFT_SET = 'TELLS_FWSHOP_CUSTOMER_ORDER_COMPLETED_GIFT_SET',
  TELLS_FWSHOP_SELLER_ORDER_CREATED = 'TELLS_FWSHOP_SELLER_ORDER_CREATED',
  TELLS_FWSHOP_SELLER_DASHBOARD_SEND_TO_CUSTOMER = 'TELLS_FWSHOP_SELLER_DASHBOARD_SEND_TO_CUSTOMER',
  TELLS_PRODUCT_AVAILABLE = 'TELLS_FWSHOP_CUSTOMER_AVAILABLE_PRODUCTS_NOTIFICATION',
  TELLS_FWSHOP_LOW_STOCK_PRODUCTS_NOTIFICATION = 'TELLS_FWSHOP_LOW_STOCK_PRODUCTS_NOTIFICATION',
  TELLS_FWSHOP_CUSTOMER_EXPERIENCE_ORDER_COMPLETED = 'TELLS_FWSHOP_CUSTOMER_EXPERIENCE_ORDER_COMPLETED',
  TELLS_FWSHOP_SELLER_EXPERIENCE_ORDER_COMPLETED = 'TELLS_FWSHOP_SELLER_EXPERIENCE_ORDER_COMPLETED',
  TELLS_FWSHOP_CUSTOMER_EXPERIENCE_ORDER_COMPLETED_MOFF_2022 = 'TELLS_FWSHOP_CUSTOMER_EXPERIENCE_ORDER_COMPLETED_MOFF_2022',
  TELLS_FWSHOP_CUSTOMER_MINT_CHARGE_MOFF_2022 = 'TELLS_FWSHOP_CUSTOMER_MINT_CHARGE_MOFF_2022',
  TELLS_FWSHOP_CUSTOMER_DEDUCTION_CHARGE_MOFF_2022 = 'TELLS_FWSHOP_CUSTOMER_DEDUCTION_CHARGE_MOFF_2022'
}
