export const DEFAULT_LIMIT = 10;
export const DEFAULT_TOP_PRODUCTS_LIMIT = 3;
export const DEFAULT_TOP_PRODUCTS_LIST_LIMIT = 13;
export const DEFAULT_TOP_PRODUCTS_LIST_LATEST_LIMIT = 18;
export const DEFAULT_PAGE_NUMBER = 1;
export const DEFAULT_TOP_EXPERIENCES_LIMIT = 1;
export const DEFAULT_TOP_GIFT_SETS_LIMIT = 12;
