export enum TaskIdEnum {
  EXCHANGE_RATES_UPDATE = 'EXCHANGE_RATES_UPDATE',
  RESOLVE_TRANSACTION_IN_TRANSIT_STATUS = 'RESOLVE_TRANSACTION_IN_TRANSIT_STATUS',
  DELETE_EXPIRED_PRODUCT_ORDER = 'DELETE_EXPIRED_PRODUCT_ORDER',
  DELETE_EXPIRED_EXPERIENCE_ORDER = 'DELETE_EXPIRED_EXPERIENCE_ORDER',
  SEND_LOW_STOCK_PRODUCT_NOTIFICATION = 'SEND_LOW_STOCK_PRODUCT_NOTIFICATION',
  SEND_PRODUCT_AVAILABLE_NOTIFICATION = 'SEND_PRODUCT_AVAILABLE_NOTIFICATION',
  SET_INSTORE_ORDER_TIMEOUT = 'SET_INSTORE_ORDER_TIMEOUT',
  RESOLVE_COIN_ACTION_QUEUE = 'RESOLVE_COIN_ACTION_QUEUE',
  CHARGE_COIN_DEDUCT = 'CHARGE_COIN_DEDUCT'
}
