export * from './create-instore-order.testsuite';
export * from './get-instore-order.testsuite';
export * from './cancel-instore-order.testsuite';
export * from './delete-instore-order-detail.testsuite';
export * from './add-more-instore-order-item.testsuite';
export * from './delete-instore-order.testsuite';
export * from './get-checkout-instore-order.testsuite';
export * from './get-all-instore-order-payment.testsuite';
export * from './clone-instore-order-group.testsuite';
