import { QueryInterface } from 'sequelize';

import { LanguageEnum } from '../../constants';
import { ProductLabelContentDbModel, ProductLabelDbModel, ProductLabelTypeContentDbModel, ProductLabelTypeDbModel } from '../models';

export default {
  up: (queryInterface: QueryInterface) => {
    return queryInterface.sequelize.transaction(async transaction => {
      await ProductLabelTypeDbModel.bulkCreate(
        [
          {
            id: 1,
            order: 1
          },
          {
            id: 2,
            order: 2
          },
          {
            id: 3,
            order: 3
          },
          {
            id: 4,
            order: 4
          },
          {
            id: 5,
            order: 5
          },
          {
            id: 6,
            order: 6
          },
          {
            id: 7,
            order: 7
          },
          {
            id: 8,
            order: 8
          },
          {
            id: 9,
            order: 9
          },
          {
            id: 10,
            order: 10
          },
          {
            id: 11,
            order: 11
          },
          {
            id: 12,
            order: 12
          }
        ],
        { transaction }
      );

      await ProductLabelTypeContentDbModel.bulkCreate(
        [
          {
            name: 'Fashion',
            order: 0,
            labelTypeId: 1,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Jewerly & Accessories',
            order: 1,
            labelTypeId: 2,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Household goods',
            order: 2,
            labelTypeId: 3,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Tableｗare',
            order: 3,
            labelTypeId: 4,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Home',
            order: 4,
            labelTypeId: 5,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Electronics',
            order: 5,
            labelTypeId: 6,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Office & School',
            order: 6,
            labelTypeId: 7,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Beauty & Health',
            order: 7,
            labelTypeId: 8,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Hobbies',
            order: 8,
            labelTypeId: 9,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Grumet Food & Drinks',
            order: 9,
            labelTypeId: 10,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Baby & Kids',
            order: 10,
            labelTypeId: 11,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'Daily necessities',
            order: 11,
            labelTypeId: 12,
            isOrigin: 0,
            language: LanguageEnum.ENGLISH
          },
          {
            name: 'ファッション',
            order: 0,
            labelTypeId: 1,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: 'アクセサリー',
            order: 1,
            labelTypeId: 2,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '生活雑貨',
            order: 2,
            labelTypeId: 3,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: 'キッチン＆ダイニング',
            order: 3,
            labelTypeId: 4,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: 'インテリア',
            order: 4,
            labelTypeId: 5,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '電子機器',
            order: 5,
            labelTypeId: 6,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '文房具',
            order: 6,
            labelTypeId: 7,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '美容・健康',
            order: 7,
            labelTypeId: 8,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: 'ホビー',
            order: 8,
            labelTypeId: 9,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '食品・ドリンク・お酒',
            order: 9,
            labelTypeId: 10,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: 'ベビー・キッズ・おもちゃ',
            order: 10,
            labelTypeId: 11,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          },
          {
            name: '日用品',
            order: 11,
            labelTypeId: 12,
            isOrigin: 1,
            language: LanguageEnum.JAPANESE
          }
        ],
        { transaction }
      );

      await ProductLabelDbModel.bulkCreate(
        [
          { id: 1, typeId: 1, order: 1 },
          { id: 2, typeId: 1, order: 2 },
          { id: 3, typeId: 1, order: 3 },
          { id: 4, typeId: 1, order: 4 },
          { id: 5, typeId: 1, order: 5 },
          { id: 6, typeId: 1, order: 6 },
          { id: 7, typeId: 1, order: 7 },
          { id: 8, typeId: 1, order: 8 },
          { id: 9, typeId: 1, order: 9 },
          { id: 10, typeId: 1, order: 10 },
          { id: 11, typeId: 1, order: 11 },
          { id: 12, typeId: 1, order: 12 },
          { id: 13, typeId: 1, order: 13 },
          { id: 14, typeId: 1, order: 14 },
          { id: 15, typeId: 1, order: 15 },
          { id: 16, typeId: 1, order: 16 },
          { id: 17, typeId: 1, order: 17 },
          { id: 18, typeId: 1, order: 18 },
          { id: 19, typeId: 1, order: 19 },
          { id: 20, typeId: 1, order: 20 },
          { id: 21, typeId: 1, order: 21 },
          { id: 22, typeId: 1, order: 22 },
          { id: 23, typeId: 2, order: 1 },
          { id: 24, typeId: 2, order: 2 },
          { id: 25, typeId: 2, order: 3 },
          { id: 26, typeId: 2, order: 4 },
          { id: 27, typeId: 2, order: 5 },
          { id: 28, typeId: 2, order: 6 },
          { id: 29, typeId: 2, order: 7 },
          { id: 30, typeId: 2, order: 8 },
          { id: 31, typeId: 3, order: 1 },
          { id: 32, typeId: 3, order: 2 },
          { id: 33, typeId: 3, order: 3 },
          { id: 34, typeId: 3, order: 4 },
          { id: 35, typeId: 3, order: 5 },
          { id: 36, typeId: 3, order: 6 },
          { id: 37, typeId: 3, order: 7 },
          { id: 38, typeId: 3, order: 8 },
          { id: 39, typeId: 4, order: 1 },
          { id: 40, typeId: 4, order: 2 },
          { id: 41, typeId: 4, order: 3 },
          { id: 42, typeId: 4, order: 4 },
          { id: 43, typeId: 4, order: 5 },
          { id: 44, typeId: 4, order: 6 },
          { id: 45, typeId: 4, order: 7 },
          { id: 46, typeId: 4, order: 8 },
          { id: 47, typeId: 4, order: 9 },
          { id: 48, typeId: 4, order: 10 },
          { id: 49, typeId: 4, order: 11 },
          { id: 50, typeId: 4, order: 12 },
          { id: 51, typeId: 4, order: 13 },
          { id: 52, typeId: 4, order: 14 },
          { id: 53, typeId: 4, order: 15 },
          { id: 54, typeId: 4, order: 16 },
          { id: 55, typeId: 4, order: 17 },
          { id: 56, typeId: 4, order: 18 },
          { id: 57, typeId: 4, order: 19 },
          { id: 58, typeId: 5, order: 1 },
          { id: 59, typeId: 5, order: 2 },
          { id: 60, typeId: 5, order: 3 },
          { id: 61, typeId: 5, order: 4 },
          { id: 62, typeId: 5, order: 5 },
          { id: 63, typeId: 5, order: 6 },
          { id: 64, typeId: 5, order: 7 },
          { id: 65, typeId: 5, order: 8 },
          { id: 66, typeId: 5, order: 9 },
          { id: 67, typeId: 5, order: 10 },
          { id: 68, typeId: 5, order: 11 },
          { id: 69, typeId: 5, order: 12 },
          { id: 70, typeId: 6, order: 1 },
          { id: 71, typeId: 6, order: 2 },
          { id: 72, typeId: 6, order: 3 },
          { id: 73, typeId: 6, order: 4 },
          { id: 74, typeId: 7, order: 1 },
          { id: 75, typeId: 7, order: 2 },
          { id: 76, typeId: 7, order: 3 },
          { id: 77, typeId: 7, order: 4 },
          { id: 78, typeId: 7, order: 5 },
          { id: 79, typeId: 7, order: 6 },
          { id: 80, typeId: 7, order: 7 },
          { id: 81, typeId: 7, order: 8 },
          { id: 82, typeId: 7, order: 9 },
          { id: 83, typeId: 7, order: 10 },
          { id: 84, typeId: 7, order: 11 },
          { id: 85, typeId: 7, order: 12 },
          { id: 86, typeId: 7, order: 13 },
          { id: 87, typeId: 7, order: 14 },
          { id: 88, typeId: 7, order: 15 },
          { id: 89, typeId: 7, order: 16 },
          { id: 90, typeId: 7, order: 17 },
          { id: 91, typeId: 7, order: 18 },
          { id: 92, typeId: 8, order: 1 },
          { id: 93, typeId: 8, order: 2 },
          { id: 94, typeId: 8, order: 3 },
          { id: 95, typeId: 8, order: 4 },
          { id: 96, typeId: 8, order: 5 },
          { id: 97, typeId: 8, order: 6 },
          { id: 98, typeId: 8, order: 7 },
          { id: 99, typeId: 8, order: 8 },
          { id: 100, typeId: 8, order: 9 },
          { id: 101, typeId: 8, order: 10 },
          { id: 102, typeId: 8, order: 11 },
          { id: 103, typeId: 8, order: 12 },
          { id: 104, typeId: 8, order: 13 },
          { id: 105, typeId: 8, order: 14 },
          { id: 106, typeId: 8, order: 15 },
          { id: 107, typeId: 8, order: 16 },
          { id: 108, typeId: 8, order: 17 },
          { id: 109, typeId: 8, order: 18 },
          { id: 110, typeId: 8, order: 19 },
          { id: 111, typeId: 8, order: 20 },
          { id: 112, typeId: 8, order: 21 },
          { id: 113, typeId: 8, order: 22 },
          { id: 114, typeId: 8, order: 23 },
          { id: 115, typeId: 8, order: 24 },
          { id: 116, typeId: 8, order: 25 },
          { id: 117, typeId: 8, order: 26 },
          { id: 118, typeId: 8, order: 27 },
          { id: 119, typeId: 8, order: 28 },
          { id: 120, typeId: 8, order: 29 },
          { id: 121, typeId: 9, order: 1 },
          { id: 122, typeId: 9, order: 2 },
          { id: 123, typeId: 9, order: 3 },
          { id: 124, typeId: 9, order: 4 },
          { id: 125, typeId: 9, order: 5 },
          { id: 126, typeId: 9, order: 6 },
          { id: 127, typeId: 10, order: 1 },
          { id: 128, typeId: 10, order: 2 },
          { id: 129, typeId: 10, order: 3 },
          { id: 130, typeId: 10, order: 4 },
          { id: 131, typeId: 10, order: 5 },
          { id: 132, typeId: 10, order: 6 },
          { id: 133, typeId: 10, order: 7 },
          { id: 134, typeId: 10, order: 8 },
          { id: 135, typeId: 10, order: 9 },
          { id: 136, typeId: 10, order: 10 },
          { id: 137, typeId: 10, order: 11 },
          { id: 138, typeId: 10, order: 12 },
          { id: 139, typeId: 10, order: 13 },
          { id: 140, typeId: 10, order: 14 },
          { id: 141, typeId: 10, order: 15 },
          { id: 142, typeId: 10, order: 16 },
          { id: 143, typeId: 10, order: 17 },
          { id: 144, typeId: 10, order: 18 },
          { id: 145, typeId: 10, order: 19 },
          { id: 146, typeId: 10, order: 20 },
          { id: 147, typeId: 10, order: 21 },
          { id: 148, typeId: 10, order: 22 },
          { id: 149, typeId: 10, order: 23 },
          { id: 150, typeId: 10, order: 24 },
          { id: 151, typeId: 10, order: 25 },
          { id: 152, typeId: 10, order: 26 },
          { id: 153, typeId: 10, order: 27 },
          { id: 154, typeId: 10, order: 28 },
          { id: 155, typeId: 10, order: 29 },
          { id: 156, typeId: 10, order: 30 },
          { id: 157, typeId: 11, order: 1 },
          { id: 158, typeId: 11, order: 2 },
          { id: 159, typeId: 11, order: 3 },
          { id: 160, typeId: 11, order: 4 },
          { id: 161, typeId: 11, order: 5 },
          { id: 162, typeId: 11, order: 6 },
          { id: 163, typeId: 11, order: 7 },
          { id: 164, typeId: 11, order: 8 },
          { id: 165, typeId: 11, order: 9 },
          { id: 166, typeId: 12, order: 1 },
          { id: 167, typeId: 12, order: 2 },
          { id: 168, typeId: 12, order: 3 },
          { id: 169, typeId: 12, order: 4 },
          { id: 170, typeId: 12, order: 5 },
          { id: 171, typeId: 12, order: 6 },
          { id: 172, typeId: 12, order: 7 },
          { id: 173, typeId: 12, order: 8 },
          { id: 174, typeId: 12, order: 9 },
          { id: 175, typeId: 12, order: 10 },
          { id: 176, typeId: 12, order: 11 },
          { id: 177, typeId: 12, order: 12 },
          { id: 178, typeId: 12, order: 13 },
          { id: 179, typeId: 12, order: 14 }
        ],
        { transaction }
      );

      await ProductLabelContentDbModel.bulkCreate(
        [
          { labelId: 1, name: 'トップス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 1, name: 'Tops', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 2, name: 'シャツ・ブラウス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 2, name: 'Shirts & Blouses', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 3, name: 'ジャケット・アウター', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 3, name: 'Jackets/ Coats', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 4, name: 'カーディガン・羽織り', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 4, name: 'Cardigan', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 5, name: 'パンツ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 5, name: 'Pants & Capris', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 6, name: 'ジーンズ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 6, name: 'Jeans', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 7, name: 'スカート', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 7, name: 'Skirts & Skorts', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 8, name: 'オールインワン・サロペット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 8, name: 'Overalls', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 9, name: 'スウェット・パーカー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 9, name: 'Sweatshirts&Fashion Hoodies', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 10, name: 'ドレス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 10, name: 'Dresses', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 11, name: 'フォーマルスーツ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 11, name: 'Formal Wear/ Suit', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 12, name: 'バッグ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 12, name: 'Bag', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 13, name: 'シューズ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 13, name: 'Shoes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 14, name: '帽子', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 14, name: 'Hats & Caps', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 15, name: 'スカーフ・マフラー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 15, name: 'Scarfs', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 16, name: '手袋', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 16, name: 'Gloves', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 17, name: '靴下', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 17, name: 'Socks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 18, name: '財布', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 18, name: 'Wallet', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 19, name: 'アンダーウェア', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 19, name: 'Underwear', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 20, name: 'ルームウェア', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 20, name: 'Sleepwear & Ropes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 21, name: 'スポーツウェア', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 21, name: 'Active', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 22, name: 'その他', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 22, name: 'Others', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 23, name: 'ピアス・イヤリング', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 23, name: 'Earings & Ear clips', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 24, name: 'ネックレス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 24, name: 'Neckles', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 25, name: 'ヘアアクセサリー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 25, name: 'Hair Accesories', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 26, name: 'ブレスレット・バングル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 26, name: 'Bracelet & Bangle', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 27, name: 'リング', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 27, name: 'Ring', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 28, name: 'アンクレット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 28, name: 'Anklets', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 29, name: 'サングラス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 29, name: 'Sunglasses', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 30, name: 'ベルト', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 30, name: 'Belts', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 31, name: 'タオル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 31, name: 'Towels', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 32, name: 'ハンカチ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 32, name: 'Handkerchiefs', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 33, name: 'ティッシュ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 33, name: 'Tissue', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 34, name: '歯ブラシ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 34, name: 'Toothblushes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 35, name: '歯磨き粉', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 35, name: 'Toothpaste', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 36, name: 'スリッパ・ルームシューズ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 36, name: 'Slippers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 37, name: 'ろうそく', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 37, name: 'Candles', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 38, name: 'キャンドルスタンド', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 38, name: 'Candle stands', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 39, name: 'マグカップ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 39, name: 'Mugs', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 40, name: 'ティーカップ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 40, name: 'Tea cups', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 41, name: 'コップ・グラス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 41, name: 'Cups & Glasses', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 42, name: 'お皿・ボウル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 42, name: 'Dishes & Bowls', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 43, name: 'お茶碗', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 43, name: 'Rice Bowls', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 44, name: '鍋', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 44, name: 'Pots', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 45, name: '箸', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 45, name: 'Chopsticks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 46, name: 'スプーン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 46, name: 'Spoons', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 47, name: 'フォーク', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 47, name: 'Forks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 48, name: 'ナイフ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 48, name: 'Knives', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 49, name: 'まな板', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 49, name: 'Cutting boards', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 50, name: '弁当箱', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 50, name: 'Lunch boxes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 51, name: 'エプロン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 51, name: 'Aprons', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 52, name: 'キッチンマット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 52, name: 'Kitchen mats', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 53, name: 'キッチンクロス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 53, name: 'Kitchen cloth', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 54, name: 'お盆・トレー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 54, name: 'Trays', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 55, name: '布巾', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 55, name: 'Towels', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 56, name: '水筒', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 56, name: 'Waterbottles', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 57, name: 'タンブラー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 57, name: 'Tumblers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 58, name: '照明', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 58, name: 'Lights', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 59, name: '収納ボックス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 59, name: 'Storage Boxes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 60, name: 'クッション', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 60, name: 'Cushions', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 61, name: 'カーペット・ラグ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 61, name: 'Carpets & Rugs', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 62, name: 'マットレス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 62, name: 'Mattless', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 63, name: '枕', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 63, name: 'Pillow', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 64, name: '布団', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 64, name: 'Bed cover', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 65, name: 'フォトフレーム', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 65, name: 'Photo frames', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 66, name: '貯金箱', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 66, name: 'Piggy banks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 67, name: '花瓶', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 67, name: 'Vases', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 68, name: '時計', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 68, name: 'Clocks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 69, name: 'ごみ箱', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 69, name: 'Trash can', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 70, name: 'マウス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 70, name: 'Wireless mouses', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 71, name: 'イヤフォン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 71, name: 'Earphones', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 72, name: 'ヘッドフォン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 72, name: 'Headphones', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 73, name: '電卓', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 73, name: 'Calculators', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 74, name: 'ボールペン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 74, name: 'Ballpoint pens', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 75, name: '万年筆', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 75, name: 'Fountain pens', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 76, name: 'シャープペン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 76, name: 'Mechanical pencils', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 77, name: 'カラーペン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 77, name: 'Markers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 78, name: '鉛筆', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 78, name: 'Pencils', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 79, name: '鉛筆削り', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 79, name: 'Pencil sharpners', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 80, name: '消しゴム', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 80, name: 'Erasers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 81, name: 'ノート・手帳', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 81, name: 'Notebooks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 82, name: '封筒', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 82, name: 'Envelops', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 83, name: 'クリップ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 83, name: 'Clips', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 84, name: 'はさみ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 84, name: 'Scissors', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 85, name: 'のり・接着剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 85, name: 'Glues ', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 86, name: 'テープ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 86, name: 'Tapes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 87, name: 'ホッチキス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 87, name: 'Staplers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 88, name: '穴あけパンチ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 88, name: 'Hole punchers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 89, name: '定規', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 89, name: 'Rulers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 90, name: 'ペンケース', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 90, name: 'Pencil cases', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 91, name: 'その他の文具', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 91, name: 'Other stationery', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 92, name: '香水', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 92, name: 'Perfumes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 93, name: 'フレグランス', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 93, name: 'Cologne', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 94, name: '日焼け止め', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 94, name: 'Sunscreen', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 95, name: '化粧水', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 95, name: 'Lotion', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 96, name: '乳液', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 96, name: 'Moisturizers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 97, name: 'オイル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 97, name: 'Oil', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 98, name: '化粧下地', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 98, name: 'Makeup base', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 99, name: 'ファンデーション', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 99, name: 'Foundation', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 100, name: 'パウダー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 100, name: 'Face Powder', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 101, name: 'アイブロウ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 101, name: 'Eyebrow pencils & Powder', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 102, name: 'アイライン', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 102, name: 'Eyeliners', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 103, name: 'アイシャドウ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 103, name: 'Eyeshadow', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 104, name: 'マスカラ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 104, name: 'Mascaras', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 105, name: 'チーク', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 105, name: 'Blushers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 106, name: 'リップ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 106, name: 'Lipsticks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 107, name: 'ネイル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 107, name: 'Nail polish', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 108, name: 'ネイル落とし', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 108, name: 'Nail polish remover', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 109, name: '化粧落とし', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 109, name: 'Cleasing', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 110, name: '洗顔', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 110, name: 'Face wash', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 111, name: 'シャンプー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 111, name: 'Shampoo', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 112, name: 'コンディショナー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 112, name: 'Conditioner', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 113, name: 'トリートメント', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 113, name: 'Treatment', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 114, name: '石鹸', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 114, name: 'Soap', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 115, name: 'ボディソープ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 115, name: 'Body soap', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 116, name: 'シェービングジェル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 116, name: 'Shaving gel', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 117, name: 'ヘアオイル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 117, name: 'Hair oil', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 118, name: 'ヘアバーム', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 118, name: 'Hair balm', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 119, name: 'ヘアブラシ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 119, name: 'Hair blush', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 120, name: 'ボディクリーム', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 120, name: 'Body cream', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 121, name: 'アート・美術品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 121, name: 'Artworks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 122, name: '工芸品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 122, name: 'Craft products', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 123, name: '手芸用品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 123, name: 'Handicraft supplies', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 124, name: '観葉植物', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 124, name: 'Indoor plants', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 125, name: '花・種', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 125, name: 'Flowers & Seeds', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 126, name: 'ガーデニング用品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 126, name: 'Home gardening supplies', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 127, name: '米・その他穀物', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 127, name: 'Rice & other grains', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 128, name: '野菜', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 128, name: 'Vegetables', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 129, name: '果物', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 129, name: 'Fruits', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 130, name: '発酵食品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 130, name: 'Fermented food', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 131, name: '加工食品', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 131, name: 'Processed food', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 132, name: 'ジャム', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 132, name: 'Jam', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 133, name: '調味料', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 133, name: 'Spices & Seasoning', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 134, name: 'ドレッシング', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 134, name: 'Dressing', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 135, name: '缶詰', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 135, name: 'Canned food', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 136, name: '焼菓子', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 136, name: 'Baked sweets', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 137, name: 'チョコレート', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 137, name: 'Chocolates', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 138, name: 'ケーキ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 138, name: 'Cakes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 139, name: 'アイスクリーム・シャーベット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 139, name: 'Icecreams & Sherbets', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 140, name: 'ドライフルーツ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 140, name: 'Dried fruits', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 141, name: 'ナッツ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 141, name: 'Nuts', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 142, name: 'ゼリー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 142, name: 'Jelly', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 143, name: '水', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 143, name: 'Water', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 144, name: '炭酸水', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 144, name: 'Sparkling water', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 145, name: 'お茶', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 145, name: 'Tea', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 146, name: '紅茶', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 146, name: 'Black tea', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 147, name: 'コーヒー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 147, name: 'Coffee', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 148, name: '栄養ドリンク', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 148, name: 'Nurtritional drinks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 149, name: 'お酢飲料', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 149, name: 'Vinegar dringks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 150, name: '野菜・果実飲料', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 150, name: 'Vegetable and fruits drinks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 151, name: 'ココア・チョコレートドリンク', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 151, name: 'Chocolate drinks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 152, name: 'ビール・発泡酒', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 152, name: 'Beer', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 153, name: '日本酒', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 153, name: 'Sake', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 154, name: 'ウイスキー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 154, name: 'Whisky', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 155, name: 'カクテル', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 155, name: 'Cocktails', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 156, name: '焼酎', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 156, name: 'Japanese shouchu', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 157, name: 'ベビー服', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 157, name: 'Baby clothes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 158, name: 'おしゃぶり', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 158, name: 'Teething rings', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 159, name: 'よだれかけ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 159, name: 'Bibs', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 160, name: 'おむつ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 160, name: 'Diapers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 161, name: '積み木', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 161, name: 'Building bloks', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 162, name: 'お食い初め食器', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 162, name: 'Tableware set for the weaning ceremony', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 163, name: 'お絵描きセット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 163, name: 'Drawing/painting set', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 164, name: 'ぬいぐるみ・人形', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 164, name: 'Stuffed toys＆Dolls', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 165, name: 'ままごとセット', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 165, name: 'Toy set', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 166, name: '洗濯用洗剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 166, name: 'Detergent', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 167, name: '柔軟剤・加香剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 167, name: 'Softner', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 168, name: 'ハンガー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 168, name: 'Hangers', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 169, name: '掃除用具', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 169, name: 'Cleaning tools', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 170, name: '住居用洗剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 170, name: 'Regidental detergent', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 171, name: '除菌スプレー・除菌剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 171, name: 'Sanitizer', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 172, name: '便座カバー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 172, name: 'Toilet seat cover', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 173, name: 'トイレットペーパー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 173, name: 'Toilet paper', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 174, name: 'ティッシュペーパー', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 174, name: 'Tissue paper', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 175, name: 'ウェットティッシュ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 175, name: 'Wet wipes', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 176, name: 'ポケットティッシュ', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 176, name: 'Pocket tissue', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 177, name: '部屋用消臭剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 177, name: 'Room deodrant', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 178, name: 'アロマ・芳香剤', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 178, name: 'Aroma diffuser', language: LanguageEnum.ENGLISH, isOrigin: 0 },
          { labelId: 179, name: '虫除け', language: LanguageEnum.JAPANESE, isOrigin: 1 },
          { labelId: 179, name: 'Insect repellents', language: LanguageEnum.ENGLISH, isOrigin: 0 }
        ],
        { transaction }
      );
    });
  },

  down: (queryInterface: QueryInterface, Sequelize: any) => {}
};
